name: Maven CI

on:
  push:
    branches: [ main, test-remote-deploy-to-vm ]
  pull_request:
    branches: [ main, test-remote-deploy-to-vm ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cakeshop  # Assicurati che questo percorso punti alla cartella giusta

    steps:
      # Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v3

      # Test ping verso la VM per verificare la connessione
      - name: Ping the VM
        run: |
          echo "Pinging the VM at ${ secrets.REMOTE_HOST }..."
          ping -c 4 ${{ secrets.REMOTE_HOST }}

      # Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Costruzione con Maven (clean package)
      - name: Build with Maven
        run: mvn -B clean package

      # Esegui i test con Maven
      - name: Run tests
        run: mvn test

      # Log in su Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Costruzione dell'immagine Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cakeshop:latest .

      # Push dell'immagine Docker su Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cakeshop:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to remote VM via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          debug: true
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/cakeshop:latest
            docker stop cakeshop || true
            docker rm cakeshop || true
            docker run -d --name cakeshop -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/cakeshop:latest
